auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: USERNAME
    password: PASSWORD
images:
  registry.k8s.io/ingress-nginx/kube-webhook-certgen: registry.cn-hangzhou.aliyuncs.com/synchub/kube-webhook-certgen
  thingsboard/tb-gateway: registry.cn-hangzhou.aliyuncs.com/synchub/tb-gateway
  thingsboard/tb-coap-transport: registry.cn-hangzhou.aliyuncs.com/synchub/tb-coap-transport
  thingsboard/tb-http-transport: registry.cn-hangzhou.aliyuncs.com/synchub/tb-http-transport
  thingsboard/tb-node: registry.cn-hangzhou.aliyuncs.com/synchub/tb-node
  thingsboard/tb-js-executor: registry.cn-hangzhou.aliyuncs.com/synchub/tb-js-executor
  thingsboard/tb-web-ui: registry.cn-hangzhou.aliyuncs.com/synchub/tb-web-ui
  thingsboard/tb-mqtt-transport: registry.cn-hangzhou.aliyuncs.com/synchub/tb-mqtt-transport
  #bitnami/kafka: registry.cn-hangzhou.aliyuncs.com/synchub/kafka
  #bitnami/pgpool: registry.cn-hangzhou.aliyuncs.com/synchub/pgpool
  #bitnami/postgresql-repmgr: registry.cn-hangzhou.aliyuncs.com/synchub/postgresql-repmgr
  #bitnami/redis: registry.cn-hangzhou.aliyuncs.com/synchub/redis
  #bitnami/zookeeper: registry.cn-hangzhou.aliyuncs.com/synchub/zookeeper
  #quay.io/argoproj/argo-rollouts: registry.cn-hangzhou.aliyuncs.com/synchub/argo-rollouts
  #gcr.io/distroless/static: registry.cn-hangzhou.aliyuncs.com/synchub/static
  #k8s.gcr.io/etcd: registry.cn-hangzhou.aliyuncs.com/synchub/etcd
  #gcr.io/kubebuilder/kube-rbac-proxy: registry.cn-hangzhou.aliyuncs.com/synchub/kube-rbac-proxy
  #k8s.gcr.io/node-problem-detector/node-problem-detector: registry.cn-hangzhou.aliyuncs.com/synchub/node-problem-detector
  #kubesphere/kube-proxy: registry.cn-hangzhou.aliyuncs.com/synchub/kube-proxy
  
  
